rest-api-client/src/main/java/com/aiconoa/trainings/entity/Author.java
package com.aiconoa.trainings.entity;

public class Author {

	private int id;
	
	private String username;
	private String password;
	
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Override
	public String toString() {
		return "Author [id=" + id + ", username=" + username + ", password=" + password + "]";
	}

}

rest-api-client/src/main/java/com/aiconoa/trainings/entity/Evenement.java
package com.aiconoa.trainings.entity;

public class Evenement {

	private int id;
	private String title;
	private String description;
	private String image;
	
	private Author author;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Author getAuthor() {
		return author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@Override
	public String toString() {
		return "Evenement [id=" + id + ", title=" + title + ", description=" + description + "]";
	}
	
}

rest-api-client/src/main/java/com/aiconoa/trainings/entity/Film.java
package com.aiconoa.trainings.entity;

public class Film {
	
	private Long id;
	
	private String title;
	
	private Long languageId;
	

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getLanguageId() {
		return languageId;
	}

	public void setLanguageId(Long languageId) {
		this.languageId = languageId;
	}

	
	
}

rest-api-client/src/main/java/com/aiconoa/trainings/entity/Invitation.java
package com.aiconoa.trainings.entity;


public class Invitation {

	private String email;
	private String date;
	private String token;
	private String status;
	
	
	private Evenement event;
	
	
	private User user;
	
	public Invitation() {
		super();
	}
	
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Evenement getEvent() {
		return event;
	}

	public void setEvent(Evenement event) {
		this.event = event;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Invitation [user=" + user.toString() + ", event=" + event.toString() + ", status="
				+ status +"]";
	}
	
}

rest-api-client/src/main/java/com/aiconoa/trainings/entity/Participation.java
package com.aiconoa.trainings.entity;

public class Participation {
	
	private String hash;

	public Participation(String hash) {
		super();
		this.hash = hash;
	}

	public String getHash() {
		return hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}

rest-api-client/src/main/java/com/aiconoa/trainings/entity/User.java
package com.aiconoa.trainings.entity;


public class User {

	private int id;
	
	private String firstName;
	private String lastName;
	private String email;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@Override
	public String toString() {
		return "User [email=" + email + "]";
	}
	
}

src/main/java/com/aiconoa/trainings/entity/Author.java
package com.aiconoa.trainings.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="author")
public class Author {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	private String username;
	private String password;
	
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	
	@Override
	public String toString() {
		return "Author [id=" + id + ", username=" + username + ", password=" + password + "]";
	}

}

src/main/java/com/aiconoa/trainings/entity/Participation.java
package com.aiconoa.trainings.entity;

public class Participation {
	
	private String hash;

	public Participation(String hash) {
		super();
		this.hash = hash;
	}

	public String getHash() {
		return hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

}

src/main/java/com/aiconoa/trainings/jsf/AttendanceConfirmationBean.java
package com.aiconoa.trainings.jsf;

import java.io.IOException;
import java.util.logging.Logger;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.aiconoa.trainings.service.EventService;

@Named
@RequestScoped
public class AttendanceConfirmationBean {

	private static final Logger LOGGER = Logger.getLogger(AttendanceConfirmationBean.class.getName());

	@Inject
	private EventService eventService;
	
	
	private String token;
	
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public void confirm() throws IOException{
		eventService.updateStatus("confirmed", token);
		String eventId = String.valueOf(eventService.findEventIdByToken(token));
		FacesContext.getCurrentInstance().getExternalContext().redirect("event-link.xhtml?index="+eventId);
	}
	
	public void decline() throws IOException{
		eventService.updateStatus("declined", token);
		String eventId = String.valueOf(eventService.findEventIdByToken(token));
		FacesContext.getCurrentInstance().getExternalContext().redirect("event-link.xhtml?index="+eventId);
	}
}

src/main/java/com/aiconoa/trainings/jsf/BannerBean.java
package com.aiconoa.trainings.jsf;

import java.io.IOException;
import java.util.logging.Logger;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

@Named
@RequestScoped
public class BannerBean {

	private static final Logger LOGGER = Logger.getLogger(BannerBean.class.getName());
	
	public boolean getIsConnected() {
		boolean isConnected = false;
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest request = (HttpServletRequest) ec.getRequest();
		HttpSession session = request.getSession();
		if (session.getAttribute("username") != null) {
			LOGGER.info("check session");
			isConnected = true;
		}
		return isConnected;
	}

	public void invalidateSession() throws IOException {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest request = (HttpServletRequest) ec.getRequest();
		request.getSession().invalidate();
		FacesContext.getCurrentInstance().getExternalContext().redirect("list-event.xhtml");
	}

	public void goToLoginPage() throws IOException {
		LOGGER.info("redirection vers login page");
		FacesContext.getCurrentInstance().getExternalContext().redirect("login.xhtml");
	}

	public void register() throws IOException {
		LOGGER.info("redirection sur register");
		FacesContext.getCurrentInstance().getExternalContext().redirect("register.xhtml");
	}
	
	public String getSessionUsername() {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest request = (HttpServletRequest) ec.getRequest();
		HttpSession session = request.getSession();
		return session.getAttribute("username").toString();
	}

}

src/main/java/com/aiconoa/trainings/jsf/EventCreationBean.java
package com.aiconoa.trainings.jsf;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Logger;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import com.aiconoa.trainings.service.EventService;

@Named
@ViewScoped
public class EventCreationBean implements Serializable{

	private static final Logger LOGGER = Logger.getLogger(EventCreationBean.class.getName());

	@Inject
	private EventService eventService;

	private String title;
	private String description;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void register() throws IOException {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest request = (HttpServletRequest) ec.getRequest();
		HttpSession session = request.getSession();
		if (session.getAttribute("username") != null) {
			String authorIndex = session.getAttribute("id").toString();
			int authorId= Integer.parseInt(authorIndex);
			eventService.insertEvent(title, description, "", authorId);
			FacesContext.getCurrentInstance().getExternalContext().redirect("list-event.xhtml");
			} else {
			FacesContext.getCurrentInstance().getExternalContext().redirect("login.xhtml");
		}
		
		

	}

}

src/main/java/com/aiconoa/trainings/jsf/EventLinkBean.java
package com.aiconoa.trainings.jsf;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.event.Event;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import com.aiconoa.trainings.entity.Evenement;
import com.aiconoa.trainings.entity.Invitation;
import com.aiconoa.trainings.entity.Participation;
import com.aiconoa.trainings.service.EventService;

@Named
@ViewScoped
public class EventLinkBean implements Serializable{

	private static final Logger LOGGER = Logger.getLogger(EventLinkBean.class.getName());

	@Inject
	private EventService eventService;

	@Inject
	Event<Participation> myEvent;

	private Integer index;
	private String addressesParam;
	private List<List<Invitation>> invitations;

	public List<Invitation> getPendingInvitations() {
		return invitations.get(0);
	}

	public List<Invitation> getConfirmedInvitations() {
		return invitations.get(1);
	}

	public List<Invitation> getDeclinedInvitations() {
		return invitations.get(2);
	}

	public List<List<Invitation>> getInvitations() {
		return invitations;
	}

	public void load() {
		this.invitations = eventService.updateInvitationsStateOfEvent(index);
	}

	public String getAddressesParam() {
		return addressesParam;
	}

	public void setAddressesParam(String addressesParam) {
		this.addressesParam = addressesParam;
	}

	public Integer getIndex() {
		LOGGER.info("get query string index");
		return index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	public Evenement getEvent() {
		return eventService.selectEvent(index);
	}

	public void register() throws IOException{
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		HttpServletRequest request = (HttpServletRequest) ec.getRequest();
		HttpSession session = request.getSession();
		
		if (session.getAttribute("username") != null) {
			String[] adresses = addressesParam.split(";");
			for (String email : adresses) {
				if (!eventService.isEmailAlreadySet(email)) {
					int userId = eventService.insertUser(email).getId();
					String hash = eventService.generateHash(email, index);
					myEvent.fire(new Participation(hash));
					eventService.insertInvitation(email, index, userId, hash);
					load();
				}
			}
		} else {
			FacesContext.getCurrentInstance().getExternalContext().redirect("login.xhtml");
		}
	}
}

src/main/java/com/aiconoa/trainings/jsf/GuessANumberBean.java
package com.aiconoa.trainings.jsf;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.aiconoa.trainings.ejb.RandomNumberEJB;

@Named
@ViewScoped
public class GuessANumberBean implements Serializable{

	private static final Logger LOGGER = Logger.getLogger(GuessANumberBean.class.getName());
	
	private Integer numberToGuess;
	
	/*@NotEmpty
	@Min(1)
	@Max(10)*/
//	@Range(min=1, max=10)
	private Integer submittedNumber;
	
	private boolean result;
	
	@Inject
	private RandomNumberEJB randomNumberEJB;
	
	/*public GuessANumberBean() {
		numberToGuess = randomNumberEJB.generateRandomInteger(10);
	}*/
	
	@PostConstruct//pour faire les injections avant d'appeler le constructeur
	public void init(){
		numberToGuess = randomNumberEJB.generateRandomInteger(10);
	}

	public Integer getSubmittedNumber(){
		LOGGER.info(String.format("getSubmittedNumber - %s", FacesContext.getCurrentInstance().getCurrentPhaseId()));
		return submittedNumber;
	}

	public void setSubmittedNumber(Integer submittedNumber) {
		LOGGER.info(String.format("setSubmittedNumber - %s", FacesContext.getCurrentInstance().getCurrentPhaseId()));
		this.submittedNumber = submittedNumber;
	}
	
	public void guess(){
		LOGGER.info("number to guess" + numberToGuess);
		LOGGER.info(String.format("guess - %s", FacesContext.getCurrentInstance().getCurrentPhaseId()));
		result = (submittedNumber.equals(numberToGuess));
	}

	public boolean getResult() {
		LOGGER.info(String.format("getResult - %s", FacesContext.getCurrentInstance().getCurrentPhaseId()));
		return result;
	}
	
}

src/main/java/com/aiconoa/trainings/jsf/ListBean.java
package com.aiconoa.trainings.jsf;

import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class ListBean {

	private static final Logger LOGGER = Logger.getLogger(ListBean.class.getName());

	
	public List<Integer> getIntegers(){
		LOGGER.info("called getIntegers()");
		return Arrays.asList(1,2,3,4,5,6);
	}
}

src/main/java/com/aiconoa/trainings/jsf/LoginBean.java
package com.aiconoa.trainings.jsf;

import java.io.IOException;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import com.aiconoa.trainings.entity.Author;
import com.aiconoa.trainings.service.EventService;

@Named
@ApplicationScoped
public class LoginBean {
	
	@Inject
	private EventService eventService;

	private Author author = new Author();
	
	public Author getAuthor() {
		return author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public void register() throws IOException {
		if (eventService.isAuthorValid(author.getUsername(), author.getPassword())) {
			int authorId = eventService.getAuthorId(author.getUsername());
			ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
			HttpServletRequest request = (HttpServletRequest) ec.getRequest();
			HttpSession session = request.getSession();
			session.setAttribute("username", author.getUsername());
			session.setAttribute("id", authorId);
		} else {
			FacesContext.getCurrentInstance().getExternalContext().redirect("login.xhtml");
		}
		
		
		FacesContext.getCurrentInstance().getExternalContext().redirect("list-event.xhtml");
	}

}

src/main/java/com/aiconoa/trainings/jsf/QueryBean.java
package com.aiconoa.trainings.jsf;

import java.util.logging.Logger;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class QueryBean {
	
	private static final Logger LOGGER = Logger.getLogger(QueryBean.class.getName());

	
	private Integer id;

	public Integer getId() {
		LOGGER.info("get index");
		return id;
	}

	public void setId(Integer id) {
		LOGGER.info("set index");
		this.id = id;
	}
	
	public String load(){
		return "hello-jsf";
	}
	
}

src/main/webapp/attendance-confirmation.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<f:metadata>
	<f:viewParam name="token" value="#{ attendanceConfirmationBean.token }" />
<!-- 	<f:viewAction action="#{ attendanceConfirmationBean.token }" /> -->
</f:metadata>

<head>
<title>attendance confirmation</title>
</head>

<h:body>
	<h2>Attendence confirmation</h2>

	<h:form>
		<h:commandButton value="Confirm"
 			action="#{ attendanceConfirmationBean.confirm }" />
		<h:commandButton value="Decline"
 			action="#{ attendanceConfirmationBean.decline }" />
	</h:form>

</h:body>

</html>

src/main/webapp/banner.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">


<head>
<title>Banner</title>
</head>

<body>
	<h:form>
		<ui:fragment rendered="#{ not bannerBean.isConnected }">
			<h:commandButton value="Login" action="#{ bannerBean.goToLoginPage }" />
		</ui:fragment>
		<ui:fragment rendered="#{ bannerBean.isConnected }">
		#{ bannerBean.sessionUsername }
		<h:commandButton value="Logout"
				action="#{ bannerBean.invalidateSession }" />
		</ui:fragment>

		<h:commandButton value="Register" action="#{ bannerBean.register }" />
	</h:form>
	<hr />

</body>

</html>

src/main/webapp/event-creation-form.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
<title>Creation form</title>
</head>

<h:body>
	<ui:include src="banner.xhtml"></ui:include>
	<h2>Formulaire de creation</h2>
	<h:form>
		<h:outputLabel>Titre</h:outputLabel>
		<h:inputText id="title" value="#{ eventCreationBean.title }">
			<f:validateRequired for="title" />
		</h:inputText>
		<h:message for="title" />
		<br />
		<h:outputLabel>Description</h:outputLabel>
		<h:inputText id="description"
			value="#{ eventCreationBean.description }">
			<f:validateRequired for="description" />
		</h:inputText>
		<h:message for="description" />

		<h:commandButton value="Register"
			action="#{ eventCreationBean.register }" />
	</h:form>
</h:body>

</html>

src/main/webapp/event-link.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<f:metadata>
	<f:viewParam name="index" value="#{ eventLinkBean.index }" />
	<f:viewAction action="#{ eventLinkBean.load }" />
</f:metadata>

<head>
<title>Event Page</title>
<link rel="stylesheet" href="eventLink.css" />
</head>

<body>
	<ui:include src="banner.xhtml" />
	<h2>#{ eventLinkBean.event.title }</h2>
	<p>#{ eventLinkBean.event.author.username }</p>
	<p>#{ eventLinkBean.event.description }</p>

	<p>Invitations @</p>

	<h:form>
		<h:inputTextarea name="textarea" rows="10" cols="50" id="email"
			value="#{ eventLinkBean.addressesParam }">
			<f:validateRequired for="email" />
<!-- 			<f:validator binding="#{ emailValidator }" /> -->
		</h:inputTextarea>
		<h:message for="email" />
		<br />
		<h:commandButton value="Register" action="#{ eventLinkBean.register }" />
	</h:form>

	<hr />
	<h:panelGroup class="tab">
		<h:panelGroup class="tab__item">
			<h2>Pending invitations</h2>
			<h:dataTable value="#{ eventLinkBean.pendingInvitations }" var="item">
				<h:column>
					<f:facet name="header">email 
					</f:facet>
				#{ item.email }
				</h:column>
				<h:column>
					<f:facet name="header">date 
					</f:facet>
				#{ item.date }
				</h:column>

			</h:dataTable>
		</h:panelGroup>

		<h:panelGroup class="tab__item">
			<h2>Confirmed invitations</h2>
			<h:dataTable value="#{ eventLinkBean.confirmedInvitations }"
				var="item">
				<h:column>
					<f:facet name="header">email 
					</f:facet>
				#{ item.email }
				</h:column>
				<h:column>
					<f:facet name="header">date 
					</f:facet>
				#{ item.date }
				</h:column>

			</h:dataTable>
		</h:panelGroup>

		<h:panelGroup class="tab__item">
			<h2>Declined invitations</h2>
			<h:dataTable value="#{ eventLinkBean.declinedInvitations }"
				var="item">
				<h:column>
					<f:facet name="header">email 
					</f:facet>
				#{ item.email }
				</h:column>
				<h:column>
					<f:facet name="header">date
					</f:facet>
				#{ item.date }
				</h:column>
			</h:dataTable>
		</h:panelGroup>
	</h:panelGroup>
</body>


</html>

src/main/webapp/guess-a-number.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
<title>Guess a number</title>
</head>

<body>
	<h1>Guess a number</h1>
	<h:form>
		<h:outputLabel>Number to guess</h:outputLabel>
		<h:inputText id="number" value="#{ guessANumberBean.submittedNumber }">
			<!-- 		validator =#{redir vers bean}
 -->
			<f:validateLongRange minimum="1" maximum="10" />
			<f:validateRequired for="number" />
		</h:inputText>
		<h:message for="number" />
		<h:commandButton value="Guess" action="#{ guessANumberBean.guess }" />

	</h:form>

	<h:outputText value="Bravo"
		rendered="#{ guessANumberBean.result eq true }" />
	<h:outputText value="Perdu"
		rendered="#{ guessANumberBean.result eq false }" />
</body>

</html>

src/main/webapp/hello-jsf.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
<title>Hello JSF</title>
</head>

<body>
	#{ helloJSF.hello } #{ helloJSF.random }
	<h:outputText value="#{ helloJSF.random }"
		rendered="#{ helloJSF.random lt 0}" />
	<h:dataTable value="#{ listBean.integers }" var="item">
		<h:column>
			<f:facet name="header">item 
			</f:facet>#{ item }
		</h:column>
		<h:column>
			<f:facet name="header">item x2
			</f:facet>
			#{ item * 2 }</h:column>
	</h:dataTable>


</body>

</html>

src/main/webapp/list-event.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
<title>List events</title>
</head>

<body>
	<ui:include src="banner.xhtml"></ui:include>
	<h2>Events</h2>
	<h:dataTable value="#{ listEvent.events }" var="item">
		<h:column>
			<f:facet name="header">titles 
			</f:facet>
			<ui:fragment rendered="#{ listEvent.authorId eq item.author.id }">
				<h:outputLink
					value="/creation-evenements-maeliss-mithra/faces/event-link.xhtml?index=#{ item.id }">
				#{ item.title }</h:outputLink>
			</ui:fragment>
			<ui:fragment rendered="#{ not bannerBean.isConnected }">
				<h:outputLink
					value="/creation-evenements-maeliss-mithra/faces/login.xhtml">
				#{ item.title }</h:outputLink>
			</ui:fragment>
		</h:column>
		<h:column>
			<f:facet name="header">descriptions
			</f:facet>
			<ui:fragment rendered="#{ listEvent.authorId eq item.author.id }">
			#{ item.description }
			</ui:fragment>
		</h:column>
	</h:dataTable>

	<br />
	<h:form>
		<h:commandButton value="Create a new event"
			action="#{ listEvent.create }" />
	</h:form>

</body>

</html>

src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<head>
<title>Login</title>
</head>

<body>
	<h2>Login</h2>
	<h:form>
		<h:outputLabel>Username</h:outputLabel>
		<h:inputText id="username" value="#{ loginBean.author.username }">
			<f:validateRequired for="username" />
		</h:inputText>
		<h:message for="username" />
		<br />
		<h:outputLabel>Password</h:outputLabel>
		<h:inputText id="password" value="#{ loginBean.author.password }">
			<f:validateRequired for="password" />
		</h:inputText>
		<h:message for="password" />
		<br />
		<h:commandButton value="Register" action="#{ loginBean.register }" />
	</h:form>
</body>

</html>

src/main/webapp/primefaces.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Hello PrimeFaces</title>
</h:head>

<h:body>

</h:body>

</html>